project:
  type: website
  output-dir: docs

website:
  title: "Understanding Economic Systems"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gmaml
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: theme.scss
    css: styles.css



